In [12]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")

# **Ejercicio 1.**

Desarrolle una aplicación que genere un dataframe con todos los años de nuestra era (hasta el año 3000) y que, para cada uno de ellos indique:
a) el día de comienzo del año,
b) si el año es bisiesto o no y,
c) si es año secular o no.

In [13]:
df = pd.DataFrame()
result = []

for i in range(1, 3001):

    if i % 400 == 0:
        secular = True
        bisiesto = True
    elif i % 100 == 0:
        secular = False
        bisiesto = False
    elif i % 4 == 0:
        secular = False
        bisiesto = True
    else:
        secular = False
        bisiesto = False

    if i % 100 == 0:
        mult100 = True
    else:
        mult100 = False

    if i % 4 ==0:
        mult4 = True
    else:
        mult4 = False

    a=np.remainder(1+5*np.remainder((i-1),4)+4*np.remainder((i-1),100)+6*np.remainder((i-1),400),7)
    if a == 0:
        dia = "domingo"
    elif a == 1:
        dia = "lunes"
    elif a == 2:
        dia = "martes"
    elif a == 3:
        dia = "miércoles"
    elif a == 4:
        dia = "jueves"
    elif a == 5:
        dia = "viernes"
    else:
        dia = "sábado"

    row = [i, secular, bisiesto, dia, mult100, mult4]
    result.append(row)

df = pd.DataFrame(result, columns=['Año', 'Secular', 'Bisiesto', 'Comienza en', 'Múltiplo_100', 'Múltiplo_4'])
df = df.reindex(columns=['Año', 'Comienza en', 'Bisiesto', 'Secular', 'Múltiplo_100', 'Múltiplo_4'])

df

       Año Comienza en  Bisiesto  Secular  Múltiplo_100  Múltiplo_4
0        1       lunes     False    False         False       False
1        2      martes     False    False         False       False
2        3   miércoles     False    False         False       False
3        4      jueves      True    False         False        True
4        5      sábado     False    False         False       False
...    ...         ...       ...      ...           ...         ...
2995  2996     viernes      True    False         False        True
2996  2997     domingo     False    False         False       False
2997  2998       lunes     False    False         False       False
2998  2999      martes     False    False         False       False
2999  3000   miércoles     False    False          True        True

[3000 rows x 6 columns]

# **Ejercicio 2.**

Entrene un modelo de Regresión Logística que permita predecir si un año será bisiesto o no a partir de los datos de Dataframe generado en el ejercicio anterior.

In [14]:
X = df[['Año', 'Secular', 'Múltiplo_100', 'Múltiplo_4']]
y = df[['Bisiesto']]

print(X)
print(y)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

logisticregression = LogisticRegression()

logisticregression.fit(x_train, y_train.values.ravel())

predictions = logisticregression.predict(x_test)
score = logisticregression.score(x_test, y_test)
params = logisticregression.get_params(deep=True)

print(score)

       Año  Secular  Múltiplo_100  Múltiplo_4
0        1    False         False       False
1        2    False         False       False
2        3    False         False       False
3        4    False         False        True
4        5    False         False       False
...    ...      ...           ...         ...
2995  2996    False         False        True
2996  2997    False         False       False
2997  2998    False         False       False
2998  2999    False         False       False
2999  3000    False          True        True

[3000 rows x 4 columns]
      Bisiesto
0        False
1        False
2        False
3         True
4        False
...        ...
2995      True
2996     False
2997     False
2998     False
2999     False

[3000 rows x 1 columns]
1.0

In [15]:
prediccion = logisticregression.predict(X)
df['Predicción'] = pd.DataFrame(prediccion)
df = df.reindex(columns=['Año', 'Comienza en', 'Secular', 'Múltiplo_100', 'Múltiplo_4', 'Bisiesto', 'Predicción'])
df

,Año,Comienza en,Secular,Múltiplo_100,Múltiplo_4,Bisiesto,Predicción
0,1,lunes,False,False,False,False,False
1,2,martes,False,False,False,False,False
2,3,miércoles,False,False,False,False,False
3,4,jueves,False,False,True,True,True
4,5,sábado,False,False,False,False,False
...,...,...,...,...,...,...,...
2995,2996,viernes,False,False,True,True,True
2996,2997,domingo,False,False,False,False,False
2997,2998,lunes,False,False,False,False,False
2998,2999,martes,False,False,False,False,False
2999,3000,miércoles,False,True,True,False,False

# **Ejercicio 3.**

Utilice el modelo de predicción anterior para predecir si un año ingresado por el usuario es bisiesto o no.

In [17]:
year_input = input("Entre el Año: ")
year = int(year_input)

df1 = pd.DataFrame()

if year % 400 == 0:
        secular = True
        bisiesto = True
elif year % 100 == 0:
        secular = False
        bisiesto = False
elif year % 4 == 0:
        secular = False
        bisiesto = True
else:
        secular = False
        bisiesto = False

if year % 100 == 0:
        mult100 = True
else:
        mult100 = False

if year % 4 ==0:
        mult4 = True
else:
        mult4 = False

append_row = {'Año': [year], 'Secular': [secular], 'Bisiesto':[bisiesto], 'Múltiplo_100':[mult100], 'Múltiplo_4':[mult4]}
append_df1 = pd.DataFrame(data=append_row)
df1 = pd.concat([df1, append_df1], ignore_index = True)

X1 = df1[['Año', 'Secular', 'Múltiplo_100', 'Múltiplo_4']]
resultado = logisticregression.predict(X1)

a=np.remainder(1+5*np.remainder((year-1),4)+4*np.remainder((year-1),100)+6*np.remainder((year-1),400),7)

if a == 0:
    dia = "domingo"
elif a == 1:
    dia = "lunes"
elif a == 2:
    dia = "martes"
elif a == 3:
    dia = "miércoles"
elif a == 4:
    dia = "jueves"
elif a == 5:
    dia = "viernes"
else:
    dia = "sábado"

if resultado == True:
    print("Es un año bisiesto y comienza en", dia)
else:
    print("No es un año bisiesto y comienza en", dia)

Entre el Año: 2027
No es un año bisiesto y comienza en viernes